package-lock.json, package.json, src/App.jsx, src/components/Header.jsx, src/components/SideBarLeft.jsx, src/index.css, yarn.lock
=> 헤더, 사이드바 구현 #1 #2

src/components/EventInfoModal.jsx
=> 이벤트 정보 모달 댓글창 UI 구현

package-lock.json, package.json, src/components/CalendarInfoModal.jsx, yarn.lock
=> 캘린더 정보 모달 수정 기능 구현

src/pages/ProfileEdit.jsx
=> 프로필 수정 페이지 CSS

src/App.jsx, src/components/Header.jsx, src/components/InviteCode.jsx
- 버튼 hover, active 효과 
- 알파벳, 숫자만 입력 가능
- 입력 시 다음 칸으로 focus
=> 캘린 참가 코드 입력 모달

src/App.jsx, src/components/InviteCodeModal.jsx, src/components/SideBarLeft.jsx, tailwind.config.js
=> 사이드바 CSS 수정

src/components/CalendarInfoModal.jsx, src/components/CreateCalendarModal.jsx, src/components/CreateEventModal.jsx, src/components/EventInfoModal.jsx
=> 캘린더와 이벤트 정보/수정/생성 UI 수정

src/components/EventInfoModal.jsx
=> 이벤트 정보 모달 댓글 창 기능 구현

src/components/CreateEventModal.jsx, src/components/SideBarLeft.jsx
=> 이벤트 생성 모달 팝업

src/pages/ProfileEdit.jsx
Reverts PoodingDev/Evento_FE#52
=> Revert "프로필 수정 페이지 저장 후 이전 페이지 이동"

src/pages/Subscription.jsx
Reverts PoodingDev/Evento_FE#51
=> Revert "공개캘린더 검색기능 추가 구현"

src/pages/Subscription.jsx
Reverts PoodingDev/Evento_FE#54
=> Revert "Revert "공개캘린더 검색기능 추가 구현""

src/pages/ProfileEdit.jsx
Reverts PoodingDev/Evento_FE#53
=> Revert "Revert "프로필 수정 페이지 저장 후 이전 페이지 이동""

src/components/CalendarInfoModal.jsx, src/components/CreateCalendarModal.jsx, src/components/CreateEventModal.jsx, src/components/InviteCodeModal.jsx, src/components/SideBarLeft.jsx, src/pages/Calendar.jsx
=> 이벤트, 캘린더 생성/수정 모달 

src/components/DeleteAccountModal.jsx, src/components/DeleteCalendarModal.jsx, src/components/Header.jsx
=> 탈퇴와 캘린더 삭제 확인 창 UI, 프로필 드롭다운 구현

src/components/CalendarInfoModal.jsx, src/components/CreateEventModal.jsx, src/components/EventInfoModal.jsx, src/components/InviteCodeModal.jsx, src/components/SideBarLeft.jsx, src/pages/Calendar.jsx
=>  모달들 클릭시 팝업 구현 및 전체 CSS 수정

src/components/CalendarInfoModal.jsx, src/components/CreateEventModal.jsx, src/components/DeleteAccountModal.jsx, src/components/EventInfoModal.jsx, src/components/Header.jsx, src/pages/Calendar.jsx, src/pages/Profile.jsx
=> 모달 UI 전체 수정 및 누락된 상태와 기능 추가

src/App.jsx, src/components/Header.jsx, src/pages/Calendar.jsx, src/pages/LogIn.jsx, src/pages/LoginPostCode.jsx, yarn.lock
- 백엔드와 연결 전 개발 편의 위해 인가 코드 받아오면 로그인 되도록 구현
=> 헤더 드랍다운 UI 수정 및 로그인 버튼 구현

src/components/CalendarInfoModal.jsx, src/components/CreateCalendarModal.jsx, src/components/CreateEventModal.jsx, src/components/EventInfoModal.jsx
=> 전체 모달 자잘한 오류 수정

src/components/CreateEventModal.jsx, src/mocks/browser.js, src/mocks/handlers/eventHandlers.js
=> MSW 이벤트 생성 구현

src/components/CalendarInfoModal.jsx, src/components/CreateEventModal.jsx, src/components/DeleteAccountModal.jsx, src/components/SideBarLeft.jsx, src/mocks/handlers/calendarHandlers.js, src/mocks/handlers/userHandlers.js
=> API 변경 후 CRUD 및 회원 탈퇴 구현

src/components/CreateEventModal.jsx, src/components/EventInfoModal.jsx, src/mocks/handlers/eventHandlers.js
=> MSW 이벤트 CRUD 구현

src/components/CreateEventModal.jsx, src/components/EventInfoModal.jsx, src/mocks/handlers/eventHandlers.js, src/pages/Calendar.jsx
=> MSW 이벤트 CRUD

src/components/EventInfoModal.jsx, src/index.css, src/mocks/handlers/calendarHandlers.js, src/pages/ProfileEdit.jsx, src/pages/Subscription.jsx
=> MSW 구독 완성, DatePicker CSS 수정

src/pages/Calendar.jsx, src/pages/Subscription.jsx, src/styles/calendar.css
=> FullCalendar 커스텀

src/pages/Subscription.jsx
=> 검색 캘린더 CSS 수정

src/api/auth.js, src/mocks/handlers/loginHandlers.js, src/pages/LoginPostCode.jsx
=> 카카오,네이버 테스트 코드

src/components/CreateEventModal.jsx, src/components/EventInfoModal.jsx, src/pages/Calendar.jsx
=> 이벤트 CRUD 캘린더에 적용

src/components/EventInfoModal.jsx
=> 이벤트 삭제 권한 설정
